### ISSUE TITLE
Troubleshooting ideas

### ISSUE THREAD

**Issue by minkione** [Kudaes/LOLBITS#2]
Hi,
I have followed the readme step by step...
Eventually I ended up with this. And doesn't look like it supposed to be like this.

Any suggestions?

![image](https://user-images.githubusercontent.com/25242404/85119211-1346d080-b22a-11ea-896c-0d772c94fd27.png)

![image](https://user-images.githubusercontent.com/25242404/85119324-3e312480-b22a-11ea-9b85-c7f89f85695f.png)

![image](https://user-images.githubusercontent.com/25242404/85119409-6587f180-b22a-11ea-8dc1-0a820ddde6d5.png)

![image](https://user-images.githubusercontent.com/25242404/85119536-98ca8080-b22a-11ea-8400-6fcb1013b056.png)

![image](https://user-images.githubusercontent.com/25242404/85119587-aaac2380-b22a-11ea-940f-d4ebb9e1ea7c.png)

![image](https://user-images.githubusercontent.com/25242404/85119761-ee069200-b22a-11ea-8ec3-aa4eb1438573.png)

**Comment by Kudaes** [comment]
Hi Minkione,

Let me ask you some questions in order to figure it out where does the issue come from:

- Can you reach your C&C from your victim machine? A simple Ping request should be enough, just to know if they are properly connected through the network.
- Have you successfully enabled the BITS Uploads functionality in your C&C server? In order to test it, you can use bitsadmin native tool from the victim and [start a download job.](https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/bitsadmin-examples) Please let me know the result of this test.
- Have you configured the variables in both the C&C Python code and in the LOLBITS project? Remember that you need to point to your C&C server address in the LOLBITS code in order to receive the connection from the client. Also, you have to setup the preshared password to encrypt the messages sent over the network.

Best regards,

**Comment by minkione** [comment]
1) Yes. They run on same machine. Even disable FW for testing purposes.
2) I guess so.  Will try looking at that URL later. Thanks.
![image](https://user-images.githubusercontent.com/25242404/85135247-7fcfc880-b246-11ea-93f0-96a3a3c3e2a0.png)
3) Yes. I followed the README accordingly.
![image](https://user-images.githubusercontent.com/25242404/85135420-bb6a9280-b246-11ea-843b-662f2f352c00.png)
![image](https://user-images.githubusercontent.com/25242404/85135462-ccb39f00-b246-11ea-96b8-aa416c1e57b4.png)
![image](https://user-images.githubusercontent.com/25242404/85135479-d3daad00-b246-11ea-98e5-7689511f16a4.png)
![image](https://user-images.githubusercontent.com/25242404/85135507-df2dd880-b246-11ea-8f63-e0bd8f899ddb.png)
![image](https://user-images.githubusercontent.com/25242404/85135542-e9e86d80-b246-11ea-89b5-e4748938f88f.png)

**Comment by minkione** [comment]
![image](https://user-images.githubusercontent.com/25242404/85136026-acd0ab00-b247-11ea-856a-9109fd6743a4.png)

**Comment by minkione** [comment]
The only thing is not mentioned in the README is if whether the IIS server should listen at 80 or 443.
By default when you create a new website... it listen on Port 80. 
So I left it as it was. it that supposed to be ok?
![image](https://user-images.githubusercontent.com/25242404/85136439-4f892980-b248-11ea-8fa5-73259bdc2f57.png)

**Comment by Kudaes** [comment]
You can set the IIS server to listen to the port that you prefere (either 80, 443 or any other), the only requirement is to set the same port in the var **Url** of the class **LOLBITS.Program** (like httpx://yourip:yourport/). 
If you navigate to http://192.168.46.129/abcde1234 do you get a base64 encoded string? Can you retry the bitsadmin test using http intead of https (use **bitsadmin /transfer myDownloadJob /download /priority normal http://192.168.46.129/abcde1234 c:\windows\temp\file.txt**)?
Does the lolbits.exe show any error message when you execute it?

**Comment by minkione** [comment]
I see an issue on fastcgi whe I try accessing http://192.168.46.129/abcde1234
![image](https://user-images.githubusercontent.com/25242404/85147232-3b98f400-b257-11ea-9a5c-585c0a3ee93d.png)

**Comment by Kudaes** [comment]
From the README: "I recommend to grant full access rights to **Everyone** for the website directory (C:\inetpub\wwwroot\bits in the example) in order to avoid all kind of access denied errors". Try this, it might solve your problem.

**Comment by minkione** [comment]
I think I have already done it. Or I am missing something?
![image](https://user-images.githubusercontent.com/25242404/85152799-1b206800-b25e-11ea-82c1-cfe981dd6363.png)

**Comment by Kudaes** [comment]
I also tried giving permissions only to the **IIS_IUSRS** account, but as far as I know it doesnt work properly and you still get access denied errors (if you figure it out why do this happen please let me know!). Thus, give full control to **Everyone** to the web directory and it should work fine.

![everyonepng](https://user-images.githubusercontent.com/9372136/85154696-122c9800-b258-11ea-96d5-6f1660a35f89.png)

**Comment by minkione** [comment]
Still getting 500 error related to FastCGI.
Unfortunately I am not very familiar with FastCGI to figure out where is failing.
I am pretty sure that all the steps in README were done correctly though. 
Even the wfastcgi-enable installation through admin CMD.

![image](https://user-images.githubusercontent.com/25242404/85155832-eca48c00-b261-11ea-9f47-bbb3ee34f429.png)

**Comment by Kudaes** [comment]
I just followed up the README step by step and I successfully deployed the C&C infrastructure, therefore my best guess is that you have messed it up at some point of the set up process.
I recommend you to start all over the deployment in a fresh IIS server. Anyway, I get your feedback and I'll try to automate the setup process in the next upgrades of the tool through some sort of script to make it easier to use.

I hope you get it to work, just dont give up! Best regards.

**Comment by minkione** [comment]
May suggest a video installation?

As developer of the tool you may give for granted things... That a new user may not have thought of.

**Comment by minkione** [comment]
The key for a FOSS tool to become popular is to smooth the learning curve for new users.

Example as for SILENTRINITY or Empire.

**Comment by Kudaes** [comment]
I agree with you, I'll work on some fixes to make it easier for new users.

**Comment by Kudaes** [comment]
Hi again @minkione,

I've released a setup ps1 script to automate the whole infrastructure deployment. You can find it now in the master branch. May you pls try it when you have some free time and give me your feedback? I'd like to know if this meets the goal of making the setup process easier.

Thank you.
